all:
  children:
    webservers:
      hosts:
        jenkins:
          ansible_host: 3.84.103.205
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/gautam/.ssh/devops-key
