all:
  children:
    webserver:
      hosts:
        jenkins:
          ansible_host: 13.217.170.123
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/gautam/.ssh/devops-key
